#!/bin/bash
if [[ -x /usr/sbin/ovmd ]] ; then
   TMP_FILE="/tmp/.ovmd_data.$$"
   TMP_VARS_FILE="/tmp/.vars_data.$$"
   VARS_FILE="/var/cfengine/state/ovmd_vars_data"

   touch $TMP_VARS_FILE
   touch $VARS_FILE
   /usr/sbin/ovmd -l | /bin/sed "s/{//g;s/}//g;s/\"//g" | awk -F: '{print $1,$2}' > $TMP_FILE

   cp -f $VARS_FILE $TMP_VARS_FILE

   while read TAG VALUE
   do
     # Look for the correct cfengine classes tag
     if [[ `echo $TAG | egrep -ic "^cfengine.vars*"` == 1 ]] ; then
	# Extract the var value from the tag
	VAR=`echo $TAG | awk -F\. '{print $3}'`
		# If not in vars file then add
		if [[ `grep -ic $VAR $VARS_FILE` == 0 ]] ; then
			cp -f $VARS_FILE $TMP_VARS_FILE
  			/bin/echo "=$VAR=$VALUE" >> $TMP_VARS_FILE
			cp -f $TMP_VARS_FILE $VARS_FILE
			ovmd -r $TAG > /dev/null
		fi
     fi
   done < $TMP_FILE
   rm $TMP_FILE $TMP_VARS_FILE

   #Post results to cfengine
   for LINE in $(cat $VARS_FILE); do echo $LINE;done
else
   exit 0
fi
