#!/bin/bash
if [[ -x /usr/sbin/ovmd ]] ; then
   TMP_FILE="/tmp/.ovmd_data.$$"
   TMP_CLASSES_FILE="/tmp/.class_data.$$"
   CLASSES_FILE="/var/cfengine/state/ovmd_class_data"

   touch $TMP_CLASSES_FILE
   touch $CLASSES_FILE
   /usr/sbin/ovmd -l | /bin/sed "s/{//g;s/}//g;s/\"//g" | awk -F: '{print $1,$2}' > $TMP_FILE

   cp -f $CLASSES_FILE $TMP_CLASSES_FILE

   while read TAG VALUE
   do
     # Look for the correct cfengine classes tag
     if [[ `echo $TAG | egrep -ic "^cfengine.classes*"` == 1 ]] ; then
   	# Extract the class vlaue from the tag
	CLASS=`echo $TAG | awk -F\. '{print $3}'`
	if [[ $VALUE == "enable" ]] ; then
		# If not in classes file then add
		if [[ `grep -ic $CLASS $CLASSES_FILE` == 0 ]] ; then
			cp -f $CLASSES_FILE $TMP_CLASSES_FILE
  			/bin/echo "+$CLASS" >> $TMP_CLASSES_FILE
			cp -f $TMP_CLASSES_FILE $CLASSES_FILE
			ovmd -r $TAG > /dev/null
		fi
	elif [[  $VALUE == "disable" ]] ; then
		# Remove from classes file
		sed '/'"$CLASS"'/d' $CLASSES_FILE > $TMP_CLASSES_FILE
		cp -f $TMP_CLASSES_FILE $CLASSES_FILE
		ovmd -r $TAG > /dev/null
	fi
     fi
   done < $TMP_FILE
   rm $TMP_FILE $TMP_CLASSES_FILE

   #Post results to cfengine
   for LINE in $(cat $CLASSES_FILE); do echo $LINE;done
else
   exit 0
fi
